---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: UTC

    cooldown:
      default-days: 7

    open-pull-requests-limit: 5

    commit-message:
      prefix: chore

    labels:
      - dependencies
      - github-actions

    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /

    schedule:
      interval: weekly
      day: monday
      time: '05:30'
      timezone: UTC

    cooldown:
      default-days: 7
      semver-major-days: 21
      semver-minor-days: 7
      semver-patch-days: 3

    open-pull-requests-limit: 5

    commit-message:
      prefix: chore

    labels:
      - dependencies
      - npm

    groups:
      content-platform:
        applies-to: version-updates
        patterns:
          - '@rm-industries/content-model'
          - astro
          - '@sveltia/cms'
        update-types:
          - minor
          - patch
      production-dependencies:
        applies-to: version-updates
        dependency-type: production
        exclude-patterns:
          - '@sveltia/cms'
          - '@rm-industries/content-model'
        update-types:
          - minor
          - patch
      development-dependencies:
        applies-to: version-updates
        dependency-type: development
        exclude-patterns:
          - astro
        update-types:
          - minor
          - patch
