import { defineConfig } from 'cspell';

export default defineConfig({
  ignorePaths: ['node_modules', 'dist', 'coverage', 'playwright-report', 'test-results', '.lighthouseci'],
  words: [
    'affordances',
    'Arroz',
    'autorun',
    'Catppuccin',
    'daisyui',
    'EAPS',
    'EVMS',
    'Fira',
    'fontsource',
    'GWSAS',
    'Himawari',
    'jsonresume',
    'keepalive',
    'Killian',
    'labelledby',
    'lhci',
    'lighthouseci',
    'lighthouserc',
    'lucide',
    'macchiato',
    'Mbps',
    'Mohandas',
    'noreferrer',
    'oxlint',
    'prefersdark',
    'rahul',
    'rahulmohandas',
    'RFIMS',
    'sveltia',
    'transpiles',
    'WCAG',
    'workstream',
    'workstreams',
    'worktree',
    'Zaccheo',
    'zizmor',
  ],
});
