import { defineConfig } from 'cspell';

export default defineConfig({
  ignorePaths: ['node_modules'],
  words: [
    'Ansible',
    'Arroz',
    'catppuccin',
    'Clearcase',
    'cooldown',
    'daisyui',
    'Decompiling',
    'EVMS',
    'Himawari',
    'keepalive',
    'Killian',
    'linkedin',
    'macchiato',
    'Mohandas',
    'oxlint',
    'pudevelopers',
    'Rahul',
    'rahulmohandas',
    'raspberrypi',
    'RFIMS',
    'sveltia',
    'vexrobotics',
    'zizmor',
    'zizmorcore',
  ],
});
