---
name: 'Setup Project Dependencies'
description: 'Sets up the project runtime and installs dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup runtime
      uses: actions/setup-node@v6 # zizmor: ignore[unpinned-uses]
      with:
        node-version: lts/*
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
