---
name: Baseline Continuous Integration

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

permissions: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-project
      - run: npm run format

  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-project
      - run: npm run lint:code

  lint-css:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-project
      - run: npm run lint:css

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-project
      - run: npm run spellcheck
