---
name: Build and Deploy Astro Site to GitHub Pages

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - name: Setup Node.js project
        uses: ./.github/actions/setup-node-project
      - name: Build site
        run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5 # zizmor: ignore[unpinned-uses]
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # zizmor: ignore[unpinned-uses]
