---
name: Deploy Site to GitHub Pages

on: # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
      - Baseline Continuous Integration
    types:
      - completed

permissions: {}

jobs:
  build:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false
      - name: Setup Node.js project
        uses: ./.github/actions/setup-node-project
      - name: Build site
        run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5 # zizmor: ignore[unpinned-uses]
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # zizmor: ignore[unpinned-uses]
