---
name: Project Continuous Integration and Deployment

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Check formatting
        run: npm run format

  lint-code:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Lint code
        run: npm run lint:code

  lint-styles:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Lint styling
        run: npm run lint:css

  spellcheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Spellcheck
        run: npm run spellcheck

  build:
    needs:
      - format
      - lint-code
      - lint-styles
      - spellcheck

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Build project
        run: npm run build

      - name: Upload GitHub Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v5 # zizmor: ignore[unpinned-uses]
        with:
          path: ./dist

  deploy:
    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # zizmor: ignore[unpinned-uses]
