---
name: Repository Meta Continuous Integration

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
  push:
    branches:
      - '**'
    paths:
      - '.github/**'

permissions: {}

jobs:
  actions:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.5.7 # zizmor: ignore[unpinned-uses]
